apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-cluster
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - name: http
      targetPort: 80
      port: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-nodeport
  namespace: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 30090
