apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secret.name }}
  namespace: {{ .Release.Name }}
type: Opaque
data:
  # Base64 encoded: echo -n 'myuser' | base64
  MYSQL_USER: bXl1c2Vy 
  # Base64 encoded: echo -n 'supersecretpass' | base64
  MYSQL_PASSWORD: c3VwZXJzZWNyZXRwYXNz 
  # Base64 encoded: echo -n 'rootpassword' | base64 (Optional, if you want a non-default root pass)
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=

