apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  clusterIP: 10.103.73.51
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
