apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: database
  clusterIP: 10.103.73.51
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
